# Generated by Django 4.2.6 on 2023-10-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_time',
        ),
    ]
